### ISSUE TITLE
关于quic的session复用

### ISSUE THREAD

**Issue by zhu327** [fangdingjun/socksquic#1]
既然quic的session是能复用的, 那么socksquic_plain是否可以在启动的时候就Dial一次, 然后每来一个新的连接sess.OpenStreamSync()开一个新的stream就可以了?

复用session与不复用有什么区别呢, 我的理解复用可以0RTT

望不吝赐教

**Comment by fangdingjun** [comment]
应该可以在启动的时候就Dial一次, 新的连接sess.OpenStreamSync()开一个新的stream

复用session 可以减少 tls handshake
